select * from public."C_B"

--Q1. What  is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Total_revenue
from public."C_B" 
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from  public."C_B"
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from public."C_B")


--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as Average_Product_rating
from public."C_B"
group by item_purchased order by avg(review_rating) desc
limit 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?


select shipping_type, round(avg(purchase_amount::numeric),2) as Avg_Amount from public."C_B"
where shipping_type in ('Express','Standard') 
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--subscribers and non-subscribers?

select subscription_status, count(customer_id) as total_customer,
sum(purchase_amount) as Total_Revenue, round(avg(purchase_amount::numeric),2) as Avg_Spend
from public."C_B"
group by subscription_status



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) 
AS discount_percentage
from public."C_B"
group by item_purchased order by discount_percentage  desc 
limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total number of
--previous purchases, and show the count of each segment?

with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from public."C_B"
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select item_purchased, category,
count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) desc) as Item_rank
from public."C_B"
group by category, item_purchased)

select item_rank,item_purchased, category, total_orders
from item_counts
where item_rank <= 3



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
--subscribe?

select subscription_status, count(customer_id) as Repeat_cus from  public."C_B"
where previous_purchases >= 5 
group by subscription_status


--Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) from public."C_B"
group by age_group 
order by sum(purchase_amount) desc


